### ISSUE TITLE
Design and implement About Page.

### ISSUE THREAD

**Issue by kavindu-mane** [kavindu-mane/Eliger#8]
References : 

- [Flowbite-react](https://www.flowbite-react.com/)
- [Figma Cummunity](https://www.figma.com/community)
- [React icons](https://react-icons.github.io/react-icons/)
- [Tailwind CSS](https://tailwindcss.com/docs/installation)

**Comment by Yassin-Aru** [comment]
#12 
I hope this be enough for now ....

**Comment by kavindu-mane** [comment]
#24
